# **Bag-Of-Words**

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

In [4]:
df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

## countvectorizer is a technique from bag of word

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [6]:
bow = cv.fit_transform(df["text"])

In [7]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'dswithbappy': 1, 'write': 4, 'comment': 0}


In [8]:
bow.toarray()

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]])

In [9]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 1 1 1 0]]
[[0 2 0 1 0]]
[[1 0 1 0 1]]


In [10]:
cv.transform(['Bappy watch dswithbappy']).toarray()

array([[0, 1, 0, 1, 0]])

In [11]:
X = bow.toarray()
y = df['output']

In [12]:
y

0    1
1    1
2    0
3    0
Name: output, dtype: int64

# **N-grams**

In [13]:
df = pd.DataFrame({'text':["people watch dswithbappy",
                   "dswithbappy watch dswithbappy",
                   "people write comment",
                   "dswithbappy write comment"],"output":[1,1,0,0]})

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range= (2,2))

In [15]:
cv = CountVectorizer(ngram_range = (2,2))

In [16]:
bow = cv.fit_transform(df['text'])

In [17]:
bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 8 stored elements and shape (4, 6)>

In [18]:
print(cv.vocabulary_)

{'people watch': 2, 'watch dswithbappy': 4, 'dswithbappy watch': 0, 'people write': 3, 'write comment': 5, 'dswithbappy write': 1}


In [19]:
print(bow.toarray())

[[0 0 1 0 1 0]
 [1 0 0 0 1 0]
 [0 0 0 1 0 1]
 [0 1 0 0 0 1]]


In [20]:
from sklearn.feature_extraction.text import CountVectorizer
cvv = CountVectorizer(ngram_range = (3,3))

In [21]:
bow = cvv.fit_transform(df['text'])

In [22]:
print(cv.vocabulary_)

{'people watch': 2, 'watch dswithbappy': 4, 'dswithbappy watch': 0, 'people write': 3, 'write comment': 5, 'dswithbappy write': 1}


# **TF-IDF (Term frequency- Inverse document frequency)**

In [23]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

In [24]:
df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()



In [26]:
arr = tfidf.fit_transform(df['text']).toarray()

In [27]:
arr

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [28]:
print(tfidf.idf_)

[1.51082562 1.22314355 1.51082562 1.51082562 1.51082562]


# **small assignment by chatgpt**

In [29]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [30]:
doc1 = "I love playing football"
doc2 = "Football is love"

In [36]:
bow1 = cv.fit_transform([doc1,doc2])

In [37]:
bow1.toarray()

array([[1, 0, 1, 1],
       [1, 1, 1, 0]])

In [38]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range= (3,3))

In [39]:
doc3 = "Natural language processing is fun"

In [42]:
bow45 = cv.fit_transform([doc3])


In [43]:
print(cv.vocabulary_)

{'natural language processing': 1, 'language processing is': 0, 'processing is fun': 2}


In [46]:
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

# Example corpus of 100 docs (we'll just simulate with repeats)
docs = ["machine learning is fun"] * 2 + ["other text"] * 98

# TF-IDF
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(docs)

# Get IDF value of "machine"
idf_value = dict(zip(vectorizer.get_feature_names_out(), vectorizer.idf_))["machine"]

print("IDF(machine):", idf_value)


IDF(machine): 4.51650822817315


In [49]:
# bi grams

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range = (2,2))

In [50]:
doc55 = "Data science is cool and useful"

In [52]:
bow = cv.fit_transform([doc55])

In [54]:
print(cv.vocabulary_)

{'data science': 2, 'science is': 4, 'is cool': 3, 'cool and': 1, 'and useful': 0}
